"use client";
import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import { SessionProvider } from "next-auth/react";
import { ToastContainer } from "react-toastify";
import Footer from "./components/Footer";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" className="bg-gray-800">
      <body className={inter.className}>
        <SessionProvider>
          <Navbar />
          {children}
        </SessionProvider>
        <ToastContainer />
        <div className="align-self-end ">
          <Footer />
        </div>
      </body>
    </html>
  );
};
export default RootLayout;