"use client"
import React from 'react';
import type { Metadata } from 'next';
import './globals.css'
import { Inter } from 'next/font/google';
import Navbar from './components/Navbar';
import { SessionProvider } from "next-auth/react"
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Navbar /></SessionProvider>
          {children}
          <ToastContainer />
      </body>
    </html>
  );
}
